libraries: # Library mappings must have a colon (:) placed after them
  Anime:
    metadata_path:
    - /config/metadata/anime.yml
    settings:
      missing_path: config/missing
      asset_directory:
      - config/assets/
    operations:
      assets_for_all: false
      split_duplicates: false
      delete_unmanaged_collections: false
settings: # Can be individually specified per library as well
  cache: true
  cache_expiration: 60
  asset_folders: true
  asset_depth: 3
  create_asset_folders: true
  create_asset_directories: true
  dimensional_asset_rename: true
  sync_mode: sync
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: true
  only_filter_missing: false
  show_unmanaged: true
  show_filtered: true
  show_options: true
  show_missing: false
  show_missing_assets: false
  show_missing_season_assets: false
  save_missing: false
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  minimum_items: 1
  default_collection_order:
  download_url_assets: true
  verify_ssl: true
  item_refresh_delay: 0
  asset_directory: config/assets
  missing_path: config/missing
  playlist_sync_to_users: all
  show_missing_episode_assets: true
  show_asset_not_needed: true
  custom_repo:
  prioritize_assets: false
  playlist_report: true
  check_nightly: false
webhooks:
  error: notifiarr
  run_start: notifiarr
  run_end: notifiarr
  changes: notifiarr
  version:
plex:                                           # Can be individually specified per library as well; REQUIRED for the script to run
  url: http://orkenstein.com:32400
  token: wqb3XHBdH_h-tLjTCnns
  timeout: 60
  clean_bundles: false
  empty_trash: false
  optimize: false
tmdb:                                           # REQUIRED for the script to run
  apikey: e55c4dbea7a6576ec29c2e86c3188786
  language: en
  cache_expiration: 60
  region:
tautulli: # Can be individually specified per library as well
  url: http://192.168.1.2:8181/
  apikey:
omdb:
  apikey:
  cache_expiration: 60
mdblist:
  apikey:
  cache_expiration: 60
notifiarr:
  apikey:
radarr: # Can be individually specified per library as well
  url: http://192.168.1.2:7878/
  token: ################################
  add_missing: ture
  add_existing: false
  root_folder_path: /media/movies
  monitor: true
  availability: released
  quality_profile: 1080p
  tag:
  search: true
  radarr_path: /media
  plex_path: /media/movies
  upgrade_existing: false
sonarr:
  url: http://192.168.1.12:32789
  token: ################################
  add_missing: ture
  add_existing: false
  root_folder_path: /media/shows
  monitor: all
  quality_profile: 1080p
  language_profile: English
  series_type: standard
  season_folder: true
  tag:
  search: true
  cutoff_search: false
  sonarr_path: /media
  plex_path: /media/shows
  upgrade_existing: false
anidb: # Not required for AniDB builders unless you want mature content
  username:
  password:
  language: en
mal: # REQUIRED for this config to work - set up by following https://metamanager.wiki/en/latest/config/myanimelist.html
  client_id: 6587c3eec1a3a501154af0adc6f78538
  client_secret: 9bcbe9af6193ed051fff933c081e9b5669498db72ba83ba5af1b4c1d52d83269
  authorization:
    access_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImY3M2IzZTRhN2FlOTI3MzgwOGMyM2JkNzBjMGQzOTBkMzRjMmNkZjRlOTkyZjJiNTUyY2VkM2EwMzNjMmY1NGIwYzUwMWFhNWIzN2YxYjAzIn0.eyJhdWQiOiI2NTg3YzNlZWMxYTNhNTAxMTU0YWYwYWRjNmY3ODUzOCIsImp0aSI6ImY3M2IzZTRhN2FlOTI3MzgwOGMyM2JkNzBjMGQzOTBkMzRjMmNkZjRlOTkyZjJiNTUyY2VkM2EwMzNjMmY1NGIwYzUwMWFhNWIzN2YxYjAzIiwiaWF0IjoxNjYwNDUzMjA3LCJuYmYiOjE2NjA0NTMyMDcsImV4cCI6MTY2MzEzMTYwNywic3ViIjoiMTUzMTY4NjIiLCJzY29wZXMiOltdfQ.Z5JEDuIgFZtd5e6SaSeoFOttnulocQ14OTWoe0mP9oHasyXvMRH_UX4e7ZyJtaVyKYFaMg-KMMQe8t-P3LK5DlKSiV8ZArl5ijumZ8en-VeDchfgTa7uOMtZzPH5WrIrIgvDTdUlxqeTJAZ9yGKZlYF6FfYtxCN3q2GfmSI0z4Vty-AR4JWeQlCvmU68vJAn0xNMqQMHGAQs25W7CZqmz_CLp2qXE3nUtZV4IXLkWXFVE7CirO6Fi4a243J4C9urVU1C3di1T8sr2J6V0JWF72JzSkb87p45b-u7QtsPj2ICcPDDGa8sgpwkRVdzqzqK2_4N-z76T1UuCNSgXRewEg
    token_type: Bearer
    expires_in: 2678400
    refresh_token: def502004e8b010a1d955231941e654c3bd4eacc18f44dcfa99b6237dc36cbd91297907e1677517f2a4b1e4cf8108c91360bb46f6df04c9425fdba17d831893f05f0510ea696c38e7a09b654d34e1612c1b0f08382e7dd9c274f2ea703bcf9aef37ee25924e1223f292d2b3d9246ac9719a247567a96a91faa7f7fff89897b8f79bf81607b87f5ab8e6ab375bcc0d4c9fcbda1697aa107d456128762b1d66dcb0888e9c0f6061d8eb3441e50b5b9934ad34af37309b4f666908ecff18138968aaa041991196d2ebdbccaa8dd0d441582d1cb05d6a07700816eaa1e30b7e83e35c6167761483bb9d08a86478e2140217d42f2fb905d20c52b64323d5112277292c91313346f5153c3fcba322d9040a904d3267cc613a4aa2ee13c6bbf5cd491a8441e9ad151294b15d5924f903edd2a8c9304e0b49a9fa944aa6bf24f381594c81ea7fd6e52e9ed9fe4d2d5db58d1666c0381c66d6c6b73ea0c700797b0f650360c6021afec269c42f0fec28c81fa7bfd4977b5454554d8ef20d70e6a5f3a76b8ab667bcc7b67ae6423
  localhost_url:
trakt:
  client_id:
  client_secret:
  authorization:
    access_token:
    token_type: Bearer
    expires_in:
    refresh_token:
    scope: public
    created_at:
  pin:
